### ISSUE TITLE
Role prefix issues

### ISSUE THREAD

**Issue by ArcAIN6** [EasternGamer/Phoenix-Bot-BETA#1]
Currently, we are trying to find a way of adding a prefix to two roles 
DMs Open
DMs Closed

The issue is, when using the bot to add the prefix upon role change, it ads it just fine, but when the role is removed, or change from one to the other, it leaves the prefix intact, and adds the new prefix.. 

It would be a big plus if the prefix was removed when the role is. 

Am i doing something wrong?

**Comment by EasternGamer** [comment]
Please join my discord and post the problem there. I would like to join your server to see it. Might be a Unicode issue. Where it saves the Unicode and then the Unicode it is meant to remove is missing because of a slight difference.

EDIT: Discord is -> https://discord.gg/RuK3Sw6

**Comment by EasternGamer** [comment]
Issue Resolved!
For others that have this **issue***, you will need to do is to remove the space you create after the emoji. For example: 

```css 
!prefix @role <emoji >
BECOMES
!prefix @role <emoji>
```

*This is ONLY if you have the issue. Under normal circumstances, there should be no problems with adding a space. This has been tested and is related more to the bot not receiving the remove role event.
